### PR TITLE
Add wake typecheck CI

### PR DESCRIPTION
**Pull request by mmjconolly**
This adds a wake 0.19.0 typecheck CI test

Also bumps the api-languages-sifive dependency

### CODE REVIEW

**Comment by mmjconolly** [comment]
Looking at the CI failure
```
Missing DEF after GLOBAL at 'topic' (api-languages-sifive/command.wake:79:[8-12])
Was expecting a EQUALS, but got a COLON at ':' (api-languages-sifive/command.wake:79:25)
Duplicate def preinstall at 'Unit => Result String Error' (api-languages-sifive/command.wake:79:[27-53]) and 'preinstall Unit' (api-languages-sifive/command.wake:80:[12-26])
Duplicate global preinstall at 'Unit => Result String Error' (api-languages-sifive/command.wake:79:[27-53]) and 'Unit => Result String Error' (api-languages-sifive/command.wake:79:[27-53])
Variable reference 'binary =>' is unbound at api-languages-sifive/command.wake:79:[32-33]
Variable reference 'Result' is unbound at api-languages-sifive/command.wake:79:[35-40]
Variable reference 'String' is unbound at api-languages-sifive/command.wake:79:[42-47]
>>> Aborting without execution <<<
```

**Comment by mmjconolly** [comment]
Wake 0.19.0 type-check passes

I also tried to bump the environment-blockci-sifive in the existing wake-api test, it produces this failure
```
$ python3.7 -B esdk-settings-generator/generate_settings.py -o build/esdk-settings-generator/settings.mk -t spike -d esdk-settings-generator/tests/spike/design.dts # launched by: /usr/lib/wake/preload-wake .build/8.3750.in.json .build/8.3750.out.json
usage: generate_settings.py [-h] -t TYPE -d DTS [-o OUTPUT]
generate_settings.py: error: argument -o/--output: can't open 'build/esdk-settings-generator/settings.mk': [Errno 2] No such file or directory: 'build/esdk-settings-generator/settings.mk'
'<hash>' build/esdk-settings-generator/settings.mk
hash_open: build/esdk-settings-generator/settings.mk: No such file or directory
runESDKSettingsGenerator (makeESDKSettingsGeneratorOptions (source "esdk-settings-generator/tests/spike/design.dts") (sources "esdk-settings-generator/tests/spike" `core.dts`) "spike" "build/esdk-settings-generator/settings.mk"): Job = Job 3750
esdk-settings-generator/tests/test-wake-api.sh: Checking for build/esdk-settings-generator/settings.mk
esdk-settings-generator/tests/test-wake-api.sh: ERROR Failed to produce build/esdk-settings-generator/settings.mk
```

**Comment by terpstra** [comment]
I've noticed in a lot of repositories, there are missing 'mkdir' calls. I suspect these bugs were masked somehow by using the preload runner.

**Review by terpstra — APPROVED** [review]
Assuming this passes, looks good.

**Comment by terpstra** [comment]
The typecheck step is now not as useful, since the actual build now runs under 0.19.0, but I guess it also doesn't hurt.

**Review by bsousi5 — APPROVED** [review]

**Pull request merged**
