### PR TITLE
Choose the greatest common RISC-V ISA to build for

### PR DESCRIPTION
**Pull request by nategraff-sifive**
Build for a subset of ISA extensions which is maximally supported by all harts in the design.

### CODE REVIEW

**Comment by nategraff-sifive** [comment]
Friends, Romans, countrypeople, the time has come to reckon with the fact that designs with heterogeneous support for the RISC-V ISA cause a lot of problems with bare metal code, namely:
- OpenOCD can't connect to a hart which doesn't support floating point if the ELF requires floating point.
- We can't guarantee that Freedom Metal programs won't crash on harts without support for the ISA the executable is built for.

I'd like to propose this as a solution: we build Freedom Metal programs for a subset of the ISA which is supported by all harts. The result is that all Freedom Metal programs will always run on all harts of the design and OpenOCD will always be able to connect to the target with a Freedom Metal program.

The downside is that to use features which are only supported on a subset of harts, we'll need to create a means of creating and launching a binary on select harts. I think this is the Right Choice, though.

**Comment by nategraff-sifive** [comment]
For what it's worth, this doesn't cause a regression on benchmarks for u54mc/u74mc.

**Comment by bsousi5** [comment]
As an additional solution, may be an ability to exclude core/s in the DTS chosen. As most/all designs so far consist of a monitor core and homogeneous U-cores, user may only want to verify/validate just the monitor core and then main core/s.

**Review by bsousi5 — APPROVED** [review]
Otherwise LGTM

**Comment by nategraff-sifive** [comment]
> As an additional solution, may be an ability to exclude core/s in the DTS chosen. As most/all designs so far consist of a monitor core and homogeneous U-cores, user may only want to verify/validate just the monitor core and then main core/s.

I think this could work, but it requires changes on the Freedom Metal side, not on any of the configuration files. DTS overlays can just used `/delete` to remove specific CPU nodes.

**Comment by bsousi5** [comment]
> > As an additional solution, may be an ability to exclude core/s in the DTS chosen. As most/all designs so far consist of a monitor core and homogeneous U-cores, user may only want to verify/validate just the monitor core and then main core/s.
> 
> I think this could work, but it requires changes on the Freedom Metal side, not on any of the configuration files. DTS overlays can just used `/delete` to remove specific CPU nodes.

Agree Freedom Metal will need change as well as the generator/s to exclude the nodes base on the what specified in the chosen cfg.

**Pull request merged**
